const guestList = [
  { name: "Nemal Gelbert, Karen De Silva", seat: "Table 1" },
  { name: "Karen De Silva", seat: "Table 1" },
  { name: "Keisha Gellbert, Nikhil", seat: "Table 1" },
  { name: "Nikhil", seat: "Table 1" },
  { name: "Mr & Mrs Gunadesa, Shanti", seat: "Table 1" },
  { name: "Shanti (SG)", seat: "Table 1" },
  { name: "Nicholas Gunadesa", seat: "Table 1" },
  { name: "Mr & Mrs Christy Gunadesa, Dewi", seat: "Table 1" },
  { name: "Dewi", seat: "Table 1" },
  { name: "Maureen", seat: "Table 1" },
  { name: "Selena David", seat: "Table 2" },
  { name: "Dolly", seat: "Table 2" },
  { name: "Mr & Mrs Mark, Dolly", seat: "Table 2" },
  { name: "Bobby", seat: "Table 2" },
  { name: "Susan", seat: "Table 2" },
  { name: "Tanuja", seat: "Table 2" },
  { name: "Kaaydan", seat: "Table 2" },
  { name: "Mr & Mrs Premasire, Sabrina", seat: "Table 2" },
  { name: "Sabrina", seat: "Table 2" },
  { name: "Lorraine", seat: "Table 2" },
  { name: "Parovsh", seat: "Table 3" },
  { name: "Kemmishra", seat: "Table 3" },
  { name: "Nick", seat: "Table 3" },
  { name: "Kuni Aziza", seat: "Table 3" },
  { name: "Antonello", seat: "Table 3" },
  { name: "Sheena, Jonny", seat: "Table 3" },
  { name: "Jonny", seat: "Table 3" },
  { name: "Hwa Pui San (Panisha)", seat: "Table 3" },
  { name: "Hwa Pui Ling (Misha)", seat: "Table 3" },
  { name: "Sri (Kolu Baapa)", seat: "Table 4" },
  { name: "Mr & Mrs Guna Tilaka", seat: "Table 4" },
  { name: "Mr & Mrs Raffi, Jenny", seat: "Table 4" },
  { name: "Mr & Mrs Stanley Sena, Selena", seat: "Table 4" },
  { name: "Mr & Mrs Jerry, Sherry", seat: "Table 4" },
  { name: "Mr Edward", seat: "Table 4" },
  { name: "Mr & Mrs Prabagaran, Gangeswary", seat: "Table 5" },
  { name: "Ms Ruthrra", seat: "Table 5" },
  { name: "Ms Pavitrra", seat: "Table 5" },
  { name: "Mr & Mrs Raja, Jayanthi ", seat: "Table 5" },
  { name: "Mr & Mrs Voothy ", seat: "Table 5" },
  { name: "Mr & Mrs Anthony (AIS) ", seat: "Table 5" },
  { name: "Ms.Namali", seat: "Table 6" },
  { name: "Mr. Nilanga", seat: "Table 6" },
  { name: "Mr & Mrs Anthony Dass, Chitra", seat: "Table 6" },
  { name: "Mr Malene", seat: "Table 6" },
  { name: "Ms Basra (Baby aunty)", seat: "Table 6" },
  { name: "Ms Crystal", seat: "Table 6" },
  { name: "Mr & Mrs Dharma, Shanti", seat: "Table 7" },
  { name: "Mr & Mrs Raja, Sumathi", seat: "Table 7" },
  { name: "Mr & Mrs Nedunchezian (Appu), Shanti ", seat: "Table 7" },
  { name: "Vinoshini", seat: "Table 7" },
  { name: "Mr & Mrs Ganesan, Irene", seat: "Table 7" },
  { name: "Mrs Ravi", seat: "Table 7" },
  { name: "Mr & Mrs Ravinn", seat: "Table 8" },
  { name: "Mr & Mrs Rajan, Sujatha", seat: "Table 8" },
  { name: "Mr & Mrs Sanjeev", seat: "Table 8" },
  { name: "Mr Malan", seat: "Table 8" },
  { name: "Mr Kumaresan", seat: "Table 8" },
  { name: "Ms Megala", seat: "Table 8" },
  { name: "Mdm Doll ", seat: "Table 8" }

];
